language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
    global:
        # Set defaults to avoid repeating in most cases
        - NUMPY_VERSION=stable
        - MAIN_CMD='py.test'
        - CONDA_DEPENDENCIES='astropy'

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.3 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.4 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    - python setup.py

script:
    - $MAIN_CMD


notifications:
  email: false
